/* global module */
module.exports = function (grunt) {

  "use-strict";

  var pkg = grunt.file.readJSON('package.json');

  // Configure the tasks
  grunt.initConfig({
    pkg: pkg,
    meta: {
      banner:
          '// JClic.js version <%= pkg.version %> (<%= grunt.template.today("yyyy-mm-dd") %>)\n' +
          '// HTML5 player of JClic activities\n' +
          '// (c) 2000-<%= grunt.template.today("yyyy") %> Educational Telematic Network of Catalonia (XTEC)\n' +
          '// This program can be freely redistributed under the terms of the GNU General Public License\n' +
          '// WARNING: You are reading a minimized, uglifyed version of jclic.js. Full, readable source\n' +
          '// code is freely available at: <%= pkg.homepage %>\n'
    },
    jshint: {
      files: ['src/**/*.js'],
      options: {
        sub: true
      }
    },
    clean: {
      dist: {
        src: ['dist']
      },
      doc: {
        src: ['doc']
      },
      build: {
        src: ['build']
      }
    },
    po_json: {
      locales: {
        options : {
          xamd: true
        },
        files: {
          'build/AllMessages.js': {
            'en': 'locales/en.po',
            'ca': 'locales/ca.po',
            'es': 'locales/es.po'
          }
        }
      }
    },
    browserify: {
      dist: {
        files: {
          'dist/jclic.js': ['src/JClic.js']
        },
        options: {
          browserifyOptions: {
            debug: true
          },
          baseUrl: './src/',
          debug: true,
          transform: ['deamdify'],
          banner: '<%= meta.banner %>'
        }
      }
    },
    extract_sourcemap: {
      dist: {
        files: {
          'dist': ['dist/jclic.js']
        }
      }
    },
    uglify: {
      dist: {
        options: {
          // By default, build just one source map from browserify
          // sourceMap: true,
          banner: '<%= meta.banner %>',
          preserveComments: false
        },
        files: {
          'dist/jclic.min.js': ['dist/jclic.js']
        }
      }
    },
    jsdoc: {
      doc: {
        src: ['misc/jsdoc/index.md', 'src/**/*.js'],
        options: {
          destination: 'doc',
          configure: 'jsdoc.conf.json',
          template: 'node_modules/gc-jaguarjs-jsdoc'
        }
      }
    },
    copy: {
      doc: {
        files: [{src: 'misc/jsdoc/ico.png', dest: 'doc/ico.png'}]
      },
      locales: {
        options: {
          process: function(content, srcpath){
                     return '// WARNING: Autogenerated file. Do not edit.\n' +
                     '// Use "grunt locales" to update this file from "/locales"\n\n' +
                     'define({version: \'' + pkg.version + '\', messages: ' + content + '});';
                   }
        },
        src: 'build/AllMessages.js',
        dest: 'src/GlobalData.js'
      }
    },
    express: {
      all: {
        options: {
          bases: ['.'],
          port: 8080,
          hostname: '0.0.0.0',
          livereload: true,
          open: 'http://localhost:8080/test/jclic-demo/index.html'
        }
      }
    },
    watch: {
      all: {
        files: ['src/**/*.js', 'dist/*.js'],
        options: {
          livereload: true
        }
      }
    }
  });

  // Load the tasks
  // Using of "load-grunt-tasks" instead of calls to "grunt.loadNpmTasks" for each module
  //
  require("load-grunt-tasks")(grunt);

  // define the tasks
  grunt.registerTask(
      'server',
      'Starts a test server',
      ['express', 'watch']
      );

  grunt.registerTask(
      'lint',
      'Checks the JS code',
      ['jshint']
      );

  grunt.registerTask(
      'locales',
      'Process translations',
      ['clean:build', 'po_json:locales', 'copy:locales']
      );

  grunt.registerTask(
      'build',
      'cleans and compiles all',
      ['locales', 'clean:dist', 'browserify:dist', 'extract_sourcemap:dist', 'uglify:dist']
      );

  grunt.registerTask(
      'doc',
      'Generates the project documentation in "doc"',
      ['clean:doc', 'jsdoc:doc', 'copy:doc']
      );

  grunt.registerTask(
      'default',
      'builds all',
      ['build']
      );
};
